export const PROGRESS_STEP_COUNT = 16

export const PROGRESS = {
  CONSENT: 0,
  WELCOME: 1,
  INTRO: 2,
  PRETEST: 3,
  PRETEST_COMPLETE: 4,
  LESSON_INTRO: 5,
  WHAT_IS_MTG: 6,
  FIRST_GAME: 7,
  LESSON_1: 8,
  LESSON_2: 9,
  LESSON_3: 10,
  LESSON_4: 11,
  LESSON_COMPLETE: 12,
  POSTTEST: 13,
  CALCULATING: 14,
  RESULTS: 15,
}
